#!/usr/bin/env bash
#
# This script generates script code blocks in markdown documentation using a special marker
#
# Marker:
# 
# <!--gen-->
# ```
# $ command_to_run
# 
# code that will be replaced
# with STDOUT from command_to_run
# ```
# 
# Note that this script requires the empty newline after `command_to_run`
# 
# inspiration:
# https://stackoverflow.com/questions/53009153/use-sed-to-replace-text-in-code-block-with-output-of-command-at-the-top-of-the

perl -0777 -pi.bak -e 's/
    (?<=\<\!--gen--\>\n```\n)  # positive lookbehind for opening code-block
    ^(\$ (.*)\n\n)             # capture reference command
    (?^s:.*?)                  # match the rest of the code-block
    (?=```)                    # positive lookahead for closing code-block
  /
    "$1"
    .qx(
      echo generating documentation for $2 >&2;
      $2
    )
  /megx' $1

  trap "printf 'deleting temp file '; rm -v $1.bak" EXIT
