#!/usr/bin/env bash -ex
#
# This script runs the commands in one of the programming language directories
# using access tokens associated with test accounts on Pinterest. Run the
# integration_tests_prerequisitions script to set up the access tokens required
# to run this script.
#

# Verify that this script is being run in an appropriate directory,
# and select the corresponding script filename extension.
case "$(basename $(pwd))" in
    python) EXT=py ;;
    nodejs) EXT=js ;;
    *)
        echo This script must be run in the python or the nodejs directory.
        exit 1
esac

TEST1=pindexterp
TEST2=penelopepintridge
TEST3=dchaiken3407

read -s -n 1 -p "Log into the ${TEST1} (pins/boards read test) account in your web browser and hit any key to continue..."
echo "authorizing v5 token for ${TEST1}"
./scripts/get_access_token.${EXT} -a ${TEST1}_v5 -w -s pins:read,boards:read,user_accounts:read
echo "authorizing v3 token for ${TEST1}"
./scripts/get_access_token.${EXT} -a ${TEST1}_v3 -v3 -w -s read_pins,read_boards,read_users

read -s -n 1 -p "Log into the ${TEST2} (pins/boards write test) account in your web browser and hit any key to continue..."
echo "authorizing v5 token for ${TEST2}"
./scripts/get_access_token.${EXT} -a ${TEST2}_v5 -w -s pins:read,pins:write,boards:read,boards:write,user_accounts:read
echo "authorizing v3 token for ${TEST2}"
./scripts/get_access_token.${EXT} -a ${TEST2}_v3 -v3 -w -s read_pins,write_pins,read_boards,write_boards,read_users

read -s -n 1 -p "Log into the ${TEST3} (ads test) account in your web browser and hit any key to continue..."
echo "authorizing v5 token for ${TEST3}"
./scripts/get_access_token.${EXT} -a ${TEST3}_v5 -w -s ads:read,pins:read,boards:read,user_accounts:read
echo "authorizing v3 token for ${TEST3}"
./scripts/get_access_token.${EXT} -a ${TEST3}_v3 -v3 -w -s read_advertisers,read_campaigns,read_pin_promotions,read_pins,read_boards,read_users

