#!/usr/bin/env bash -ex
#
# This file runs the following scripts in the programming language directories
# using access tokens associated with a test account on Pinterest:
#   get_ads
#   get_analytics
#   analytics_api_example
#
# All of these scripts are read-only, so it should always be safe to run
# the tests in this file.
#
# The tests in this file are only self-checking to the extent that all
# should run to completion successfully. Knowledge about the test account
# and manual checking is required to verify that the tests all returned
# the expected data. Of course, it would be better to check the results
# automatically, but for now the automation focuses on running a standard
# set of tests.
#

# Verify that this script is being run in an appropriate directory,
# and select the corresponding script filename extension.
case "$(basename $(pwd))" in
    python) EXT=py ;;
    nodejs) EXT=js ;;
    *)
        echo This script must be run in the python or the nodejs directory.
        exit 1
esac

# These variables are specific to the user names, pin id, and board id
# to be used for this test.
TEST3=dchaiken3407

OUTPUT_PREFIX=integtest

# delete output files to avoid overwrite confirmations by scripts
rm -f ${OUTPUT_PREFIX}_*.json

# Versions to test. This variable should not need to change.
VERSIONS="v3 v5"

# first refresh the tokens in case it has been a while since the tests were last run
for VERSION in ${VERSIONS} ; do
    ./scripts/get_ads.${EXT} -a ${TEST3}_${VERSION} -${VERSION} --all-ads
done

# get user analytics
for VERSION in ${VERSIONS} ; do
    DOCNAME=${OUTPUT_PREFIX}_user_analytics_${VERSION}.json
    echo ${DOCNAME} | \
         ./scripts/get_analytics.${EXT} -a ${TEST3}_${VERSION} -${VERSION}
    wc ${DOCNAME}
done

# get ad_account_user analytics (only available for v5)
for VERSION in v5 ; do
    DOCNAME=${OUTPUT_PREFIX}_ad_account_user_analytics_${VERSION}.json
    printf "3\n${DOCNAME}\n" | \
         ./scripts/get_analytics.${EXT} -a ${TEST3}_${VERSION} -${VERSION} -o ad_account_user
    wc ${DOCNAME}
done

# get ad_account analytics
for VERSION in ${VERSIONS} ; do
    DOCNAME=${OUTPUT_PREFIX}_ad_account_analytics_${VERSION}.json
    printf "3\n${DOCNAME}\n" | \
         ./scripts/get_analytics.${EXT} -a ${TEST3}_${VERSION} -${VERSION} -o ad_account
    wc ${DOCNAME}
done

# get campaign analytics
for VERSION in ${VERSIONS} ; do
    DOCNAME=${OUTPUT_PREFIX}_campaign_analytics_${VERSION}.json
    printf "3\n${DOCNAME}\n" | \
         ./scripts/get_analytics.${EXT} -a ${TEST3}_${VERSION} -${VERSION} -o campaign
    wc ${DOCNAME}
done

# get ad group analytics
for VERSION in ${VERSIONS} ; do
    DOCNAME=${OUTPUT_PREFIX}_ad_group_analytics_${VERSION}.json
    printf "3\n${DOCNAME}\n" | \
         ./scripts/get_analytics.${EXT} -a ${TEST3}_${VERSION} -${VERSION} -o ad_group
    wc ${DOCNAME}
done

# get ad analytics
for VERSION in ${VERSIONS} ; do
    DOCNAME=${OUTPUT_PREFIX}_ad_analytics_${VERSION}.json
    printf "3\n1\n${DOCNAME}\n" | \
         ./scripts/get_analytics.${EXT} -a ${TEST3}_${VERSION} -${VERSION} -o ad
    wc ${DOCNAME}
done

# all tests existed successfully: delete output files
rm -f ${OUTPUT_PREFIX}_*.json
