# Documentation: https://github.com/tinovyatkin/action-php-codesniffer
name: php

on:
  pull_request:
    paths: php/**.php

defaults:
  run:
    working-directory: php

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version

      - name: Run PHP_CodeSniffer
        run: php phpcs.phar -v *.php
