name: Python

on:
  pull_request:
    paths: 'python/**.py'

defaults:
  run:
    shell: bash
    working-directory: python

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Lint
        run: make lint_check
      - name: Test
        run: make tests
